; Creado por Jonathan Garrido S. - jgarrido.spa@gmail.com
[platformio]
default_envs = lilygo-t-echo

[env:lilygo-t-echo]
platform = nordicnrf52@10.9.0
board = nrf52840_dk_adafruit
framework = arduino
monitor_speed = 115200
upload_protocol = nrfutil
upload_port = COM5
build_flags =
    -DCFG_DEBUG=0
    -DARDUINO_NRF52_ADAFRUIT
    -Iinclude
lib_deps =
    jgromes/RadioLib@^6.6.0
    zinggjm/GxEPD2@^1.6.2
    mikalhart/TinyGPSPlus@^1.0.3
    lewisxhe/PCF8563_Library@^1.0.1
